# 텐서플로우 자료구조

일반 상대성이론(general relativity) 전문가인 "Lillian Lieber"는 텐서(tensor)를 "Facts of the Universe"라고 지칭했다. 구글브레인(google brain)에서 그래프기반 수치연산(Graph-based Numerical Computation)을 위한 오픈소스 라이브러리로 [텐서플로우(tensorflow)](https://www.tensorflow.org/)를 공개했으며 2019년 Tensorflow 2.0를 공개하였는데 Eager Execution, 케라드, Estimators이 추가되었다.

텐서는 벡터와 행렬을 일반화한 것으로 숫자의 집합이라고 볼 수 있다. 행렬은 2-D 격자위에 놓은 숫자 집합으로 간주할 수 있는 반면 **텐서(tensor)** 는 일반화된 행렬로 생각할 수 있다. 

<img src="fig/tensor.jpg" alt="텐서" width="57%" />

- 참고자료
    - [Dan Fleisch, "What's a Tensor?", Youtube](https://www.youtube.com/watch?v=f5liqUk0ZTw)
    - [Manish Thapliyal (Jul 22, 2018), "Machine Learning Basics : Scalars, Vectors, Matrices and Tensors", medium](https://medium.com/@manish54.thapliyal/machine-learning-basics-scalars-vectors-matrices-and-tensors-e120ecd0e6f7)
    - [Steven Steinke (Aug 28, 2017), "What’s the difference between a matrix and a tensor?"](https://medium.com/@quantumsteinke/whats-the-difference-between-a-matrix-and-a-tensor-4505fbdc576c)

## CPU vs GPU 속도 비교

- 참고자료
    - [Tensorflow, "즉시 실행 기초"](https://www.tensorflow.org/tutorials/eager/eager_basics?hl=ko)

In [1]:
from __future__ import absolute_import, division, print_function
import utils
import tensorflow as tf
tf.enable_eager_execution()

import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.matmul(x, x)

  result = time.time()-start
    
  print("10 loops: {:0.2f}ms".format(1000*result))


# CPU에서 강제실행합니다.
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random_uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# GPU #0가 이용가능시 GPU #0에서 강제실행합니다.
print("On GPU:")
# if tf.test.is_gpu_available():
#   with tf.device("GPU:0"): # 또는 GPU:1, GPU:2
#     x = tf.random_uniform([1000, 1000])
#     assert x.device.endswith("GPU:0")
#     time_matmul(x)

On CPU:
10 loops: 88.50ms
On GPU:


# 텐서플로우 도구로 텐서 정의



## 텐서 정의

In [2]:
tf_0d = tf.ones((1,))
tf_0d

<tf.Tensor: id=19, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [3]:
tf_1d = tf.ones((2,))
tf_1d

<tf.Tensor: id=23, shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [4]:
tf_2d = tf.ones((2,2))
tf_2d

<tf.Tensor: id=27, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [5]:
tf_3d = tf.ones((2,2,2))
tf_3d

<tf.Tensor: id=31, shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

## 상수(constant) 정의

넘파이(numpy)와 마찬가지로 상수를 정의하는데 유용한 함수가 다수 지원된다.

|      연산자        |     사례        |
|:------------------|:-----------------|
| tf.constant()    | constant([1, 2, 3]) |
| tf.zeros()       | zeros([2, 2]) |
| tf.zeros_like()  | zeros_like(input_tensor) |
| tf.ones()        | ones([2, 2]) |
| tf.ones_like()   | ones_like(input_tensor) |
| tf.fill()        | fill([3, 3], 7) |

In [6]:
from tensorflow import constant

x = constant(3, shape=[2,3])
print(x)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32)


In [7]:
y = constant([1,2,3,4], shape=[2,2])
y

<tf.Tensor: id=39, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## 변수(variable) 정의

In [8]:
# 변수 정의
x = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
y = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)

# 상수, 회귀계수 정의
coef = tf.constant(5, tf.float32)
# 회귀계수와 X 곱
y_hat = tf.multiply(x, coef)

# 오차
error = tf.subtract(y, y_hat)
print(error)

tf.Tensor([ -4.  -8. -12. -16. -20. -24.], shape=(6,), dtype=float32)


## 연산

스칼라 0-D 텐서와 벡터 1-D 텐서, 행렬 2-D 텐서 연산을 수행해 보자. 각 원소별로 덧셈을 추가한다. 

In [9]:
A_T0 = constant([1])
B_T0 = constant([2])

T0 = tf.add(A_T0, B_T0)
print(T0.numpy())

[3]


In [10]:
A_T1 = constant([1,2])
B_T1 = constant([3,4])

tf.add(A_T1, B_T1)

<tf.Tensor: id=68, shape=(2,), dtype=int32, numpy=array([4, 6])>

In [11]:
A_T2 = constant([[1,2], [3,4]])
B_T2 = constant([[5,6], [7,8]])

tf.add(A_T2, B_T2)

<tf.Tensor: id=72, shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [13]:
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

x = tf.constant([1., 2.])
print(type(x))            # <type 'EagerTensor'>
print(type(x.numpy()))    # <type 'numpy.ndarray'>
print(type(np.array(x)))  # <type 'numpy.ndarray'>

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
x

<tf.Tensor: id=74, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>